### ISSUE TITLE
Create test backup of OAR collection

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dataspace_preservation#19]
Hannah would like to look at an OAR collection backup to evaluate backup and preservation for future plans for the OAR platform.

Start with [Anthropology collection](https://oar.princeton.edu/handle/88435/pr1wc7r).

**Comment by kelynch** [comment]
Likely a bug in pagination select due to differences between DataSpace and OAR layouts:

```bash
bundle exec ruby list_arks.rb -h https://oar.princeton.edu -a ark:/88435/pr1wc7r
list_arks.rb:27:in `fetch_arks': undefined method `css' for nil:NilClass (NoMethodError)

    search_table_rows = search_table.css('tr')
                                    ^^^^
	from list_arks.rb:65:in `<main>'
```

**Comment by kelynch** [comment]
OAR is migrating to Princeton Scholars Repository.
